// AUTO-GENERATED by scripts/gen-portfolio.mjs — do not edit by hand.
// To change photos: edit public/media/portfolio/ (+ captions.json), then run `npm run portfolio`.
import type { ImageAsset } from "./site";

export const portfolioImages: ImageAsset[] = [
  {
    src: "/media/portfolio/01-beauty-flowers.jpg",
    width: 854,
    height: 1280,
    alt: {
      pt: "Melissa Oliveira em retrato de beleza, deitada em um jardim de margaridas amarelas, cabelos ruivos cacheados",
      en: "Melissa Oliveira in a beauty portrait, lying in a bed of yellow daisies, red curly hair"
    }
  },
  {
    src: "/media/portfolio/02-olive-editorial.jpg",
    width: 900,
    height: 1185,
    alt: {
      pt: "Melissa Oliveira em pose editorial agachada, macacão verde militar, batom vermelho, fundo neutro",
      en: "Melissa Oliveira in a crouched editorial pose, olive-green jumpsuit, red lip, neutral backdrop"
    }
  },
  {
    src: "/media/portfolio/03-blue-studio-curls.jpg",
    width: 900,
    height: 1601,
    alt: {
      pt: "Melissa Oliveira em estúdio com fundo azul, camisa translúcida estampada, brincando com os cachos ruivos",
      en: "Melissa Oliveira in studio on a blue backdrop, sheer printed shirt, playing with her red curls"
    }
  },
  {
    src: "/media/portfolio/04-natural-ugc-selfie.jpg",
    width: 900,
    height: 1200,
    alt: {
      pt: "Melissa Oliveira em retrato natural e espontâneo, luz do dia, cabelos cacheados — estilo UGC",
      en: "Melissa Oliveira in a natural, candid daylight portrait, curly hair — UGC style"
    }
  },
  {
    src: "/media/portfolio/05-olive-crouch.jpg",
    width: 900,
    height: 1156,
    alt: {
      pt: "Melissa Oliveira em pose editorial, macacão verde militar, olhar direto para a câmera, fundo neutro",
      en: "Melissa Oliveira in an editorial pose, olive-green jumpsuit, looking straight at the camera, neutral backdrop"
    }
  },
  {
    src: "/media/portfolio/06-blue-studio-poised.jpg",
    width: 900,
    height: 1601,
    alt: {
      pt: "Melissa Oliveira em estúdio com fundo azul, mãos entrelaçadas junto ao rosto, expressão serena",
      en: "Melissa Oliveira in studio on a blue backdrop, hands clasped near her face, serene expression"
    }
  },
  {
    src: "/media/portfolio/07-studio-beauty-portrait.jpg",
    width: 1067,
    height: 1600,
    alt: {
      pt: "Melissa Oliveira em retrato de beleza em estúdio, top preto, mão ao rosto, batom vermelho",
      en: "Melissa Oliveira in a studio beauty portrait, black top, hand to face, red lip"
    }
  },
  {
    src: "/media/portfolio/08-street-denim-glasses.jpg",
    width: 1067,
    height: 1600,
    alt: {
      pt: "Melissa Oliveira em ensaio lifestyle ao ar livre, jaqueta jeans, top de renda e óculos, sentada em um banco",
      en: "Melissa Oliveira in an outdoor lifestyle shoot, denim jacket, lace top and tinted glasses, seated on a bench"
    }
  },
  {
    src: "/media/portfolio/09-blue-studio-smile.jpg",
    width: 899,
    height: 1600,
    alt: {
      pt: "Melissa Oliveira sorrindo em estúdio com fundo azul, camisa translúcida sobre top branco",
      en: "Melissa Oliveira smiling in studio on a blue backdrop, sheer shirt over a white top"
    }
  },
  {
    src: "/media/portfolio/10-blue-studio-halter.jpg",
    width: 899,
    height: 1600,
    alt: {
      pt: "Melissa Oliveira em estúdio com fundo azul, top frente-única preto e shorts jeans, mão na cintura",
      en: "Melissa Oliveira in studio on a blue backdrop, black halter top and denim shorts, hand on hip"
    }
  },
  {
    src: "/media/portfolio/11-sunlit-denim-wall.jpg",
    width: 1067,
    height: 1600,
    alt: {
      pt: "Melissa Oliveira em ensaio ao ar livre sob luz do sol, jaqueta jeans e top de renda, braço erguido junto à parede",
      en: "Melissa Oliveira in a sunlit outdoor shoot, denim jacket and lace top, arm raised against a wall"
    }
  },
  {
    src: "/media/portfolio/12-blue-studio-joy.jpg",
    width: 899,
    height: 1600,
    alt: {
      pt: "Melissa Oliveira sorrindo espontaneamente em estúdio com fundo azul, brincando com os cachos",
      en: "Melissa Oliveira laughing candidly in studio on a blue backdrop, playing with her curls"
    }
  },
  {
    src: "/media/portfolio/13-blue-studio-halter-full.jpg",
    width: 899,
    height: 1600,
    alt: {
      pt: "Melissa Oliveira em corpo inteiro em estúdio com fundo azul, top frente-única preto e shorts jeans",
      en: "Melissa Oliveira full-body in studio on a blue backdrop, black halter top and denim shorts"
    }
  },
  {
    src: "/media/portfolio/14-wood-floor-editorial.jpg",
    width: 1067,
    height: 1600,
    alt: {
      pt: "Melissa Oliveira em pose editorial sobre piso de madeira, jaqueta jeans e top de renda, olhando para a câmera",
      en: "Melissa Oliveira in an editorial pose on a wooden floor, denim jacket and lace top, looking up at the camera"
    }
  },
  {
    src: "/media/portfolio/15-blue-studio-serene.jpg",
    width: 899,
    height: 1600,
    alt: {
      pt: "Melissa Oliveira em estúdio com fundo azul, camisa translúcida sobre top branco, expressão serena",
      en: "Melissa Oliveira in studio on a blue backdrop, sheer shirt over a white top, serene expression"
    }
  }
];
